on: [push, workflow_dispatch]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.FTP_Host }}
        port: ${{ secrets.FTP_Port }}
        username: ${{ secrets.FTP_Username }}
        password: ${{ secrets.FTP_Password }}
        localPath: './'
        remotePath: './public_html'